### ISSUE TITLE
Conservatory pods 2/3

### ISSUE THREAD

**Issue by KarineNingbers** [BrookJeynes/slime-rancher-2-interactive-map#19]
3/3 Pods on conservatory that are not on the map yet (I've marked them with my own pins)

![pod1](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/8653713/79cfddb7-e9ee-49db-b569-25e1c529f325)
![pod1location](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/8653713/7cd9eb2d-516a-4358-a42b-a5f50edec8f8)
On a small alcove in the gully

![pod2](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/8653713/0a05e8a2-9988-42a7-943e-2fd43c3848d8)
On top of the tree next to the Research Drone

Edit: Found the 3rd:
![pod3](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/8653713/d8a85698-82f2-449e-98fd-0e054919766d)

**Comment by rodriguezrrp** [comment]
Thank you! This was partially addressed with #18 but the webpage itself needs updated. @BrookJeynes is the one who can update gh-pages with a new build of the site

**Comment by BrookJeynes** [comment]
@rodriguezrrp @KarineNingbers I'll make a build asap when I get home, thanks for the work guys!
