### ISSUE TITLE
Missing parts on Ember Valley map image

### ISSUE THREAD

**Issue by rodriguezrrp** [BrookJeynes/slime-rancher-2-interactive-map#21]
The Ember Valley on the map image is missing
- the large cave added along the northern ocean opening
- the teleport pad island to the south

Both related to the Powderfall Bluffs teleportation line endpoints, as is self-explanatory in this image:
![image](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/53585065/ccfc7db3-3e50-4a31-a9f1-6825adf7b99f)

**Comment by BrookJeynes** [comment]
@rodriguezrrp i'll take a look when I get home but I think the game assets didn't have them within the map chunks that I had to piece together. I'll see if I can find them and patch them in when I can 👍

**Comment by rodriguezrrp** [comment]
Okay! (I haven't been able to crack open the game assets myself.)
For completeness here is one more notable missing piece I found, this pillar in the ocean (which has a pod on it):
![image](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/53585065/37cbbf66-897c-410f-92b5-07e9e865b0dd)

**Comment by BrookJeynes** [comment]
closing as i've now added these
