### ISSUE TITLE
Missing Nodes (Ember Valley)

### ISSUE THREAD

**Issue by Cupsl** [BrookJeynes/slime-rancher-2-interactive-map#23]
There are five missing nodes in Ember Valley. I have not yet located where the missing five are but I will update on this issue when I do find them.

1/5 of the missing nodes found. Found above the Rock Gordo slime behind the rock formation.
![New Node](https://github.com/BrookJeynes/slime-rancher-2-interactive-map/assets/166653203/83ffe17f-29a8-4b4f-97cc-91489939cffc)

**Comment by BrookJeynes** [comment]
@Cupsl I've gone ahead and added that node. Did you end up finding the other missing ones by chance? :)

**Comment by BrookJeynes** [comment]
Closing as i've marked all locations

**Comment by Cupsl** [comment]
Couldn't find the other nodes since my gamepass expired. also because I couldn't find em either but thank you for your work
