### ISSUE TITLE
[Bug] Drone logs don't work on mobile

### ISSUE THREAD

**Issue by BrookJeynes** [BrookJeynes/slime-rancher-2-interactive-map#5]
## Repro Steps
1. Click Map:**Resource Drone Icon  | Access Log** on mobile
2. See log go off the screen / not size correctly

**Comment by Clearmist** [comment]
:) I've got my responsive design tool up in Firefox and don't see a log. This is my view. Are you talking about clicking the "resource drone" filter?

![2022-10-03 07_55_52-SR2 Interactive Map — Mozilla Firefox](https://user-images.githubusercontent.com/4317724/193595607-71929102-aeb3-4c8b-b488-43c59715bd7b.png)

**Comment by BrookJeynes** [comment]
@Clearmist ahh my bad, updated the original with more clarity. I was referring to when you click on a drone icon and then press the access log button on the popup.

**Comment by BrookJeynes** [comment]
@Clearmist I believe we should update it with the progress. The visual box is now fixed but we still have the issue with the text going off the screen don't we?
