### ISSUE TITLE
some radiant ores found

### ISSUE THREAD

**Issue by Minztower** [BrookJeynes/slime-rancher-2-interactive-map#6]
I found some radiant ores in the ember valley that arent on the map yet. Also, i am continuing to edit this to add more ores i find

the map locations:
1. https://cdn.discordapp.com/attachments/823885128136523811/1024363341684154398/unknown.png
2. https://cdn.discordapp.com/attachments/823885128136523811/1024363492607791134/unknown.png
3. https://cdn.discordapp.com/attachments/823885128136523811/1024363931768213524/unknown.png
4. https://cdn.discordapp.com/attachments/823885128136523811/1024366686649982986/unknown.png
5. https://cdn.discordapp.com/attachments/823885128136523811/1024368055960219718/unknown.png
6. https://cdn.discordapp.com/attachments/823885128136523811/1024370528082989166/unknown.png
7. https://cdn.discordapp.com/attachments/823885128136523811/1024375112897663026/unknown.png
the ores:
1- https://cdn.discordapp.com/attachments/823885128136523811/1024363298596077728/unknown.png
2- https://cdn.discordapp.com/attachments/823885128136523811/1024363444767555666/unknown.png
3- https://cdn.discordapp.com/attachments/823885128136523811/1024363879108714506/unknown.png
4- https://cdn.discordapp.com/attachments/823885128136523811/1024366751795908729/unknown.png
5- https://cdn.discordapp.com/attachments/823885128136523811/1024367952679686214/unknown.png
6- https://cdn.discordapp.com/attachments/823885128136523811/1024370458184929280/unknown.png
7- https://cdn.discordapp.com/attachments/823885128136523811/1024375061488074822/unknown.png

**Comment by BrookJeynes** [comment]
closing as we no longer display resource locations
