### ISSUE TITLE
Silky Sand location in Ember Valley that isn't shown on the map I noticed

### ISSUE THREAD

**Issue by CommandBlockGuru** [BrookJeynes/slime-rancher-2-interactive-map#9]
It won't let me put the image on here for some reason, but on the sandy area South in Ember Valley, near the entrance on a ledge with a HenHen nest, there's a Silky Sand collection. Sorry, I'm really bad at explaining things like this and the image won't work so

**Comment by BrookJeynes** [comment]
Closing due to us moving away from individually showing where items are
